# Uncomment this line to define a global platform for your project
# platform :ios, "7.0"

target "PludForMac" do

pod 'DTBonjour', '1.1.0'
pod 'AXStatusItemPopup', '~> 0.0'

end

target "PludForMacTests" do

end

